name: '🚔'
on:
  push:
    tags:
      - 'v[0-9]*'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'
      - run: ./gradlew clean setupDecompWorkspace build --console plain --no-daemon --full-stacktrace
      - uses: softprops/action-gh-release@v1
        with:
          body: 'Release generated at commit: ${{ github.sha }}'
          files: 'build/libs/Catalyst-*-shadow.jar'
